package util

import (
	"fmt"
	"math/rand"
	"regexp"
	"strings"
	"time"

	"github.com/brianvoe/gofakeit/v7"
)

// emailNamePattern matches local parts like "john.doe.4f2a" — firstname.lastname.hex
var emailNamePattern = regexp.MustCompile(`^([a-z]+)\.([a-z]+)\.[0-9a-f]{4}$`)

// RandomName returns a random first and last name using gofakeit.
func RandomName() (string, string) {
	return gofakeit.FirstName(), gofakeit.LastName()
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// ParseNameFromEmail extracts first and last name from emails generated by the cloudflare
// temp mail worker (format: firstname.lastname.hex@domain). Returns false if format doesn't match.
func ParseNameFromEmail(emailAddr string) (firstName, lastName string, ok bool) {
	local := strings.SplitN(emailAddr, "@", 2)[0]
	m := emailNamePattern.FindStringSubmatch(local)
	if m == nil {
		return "", "", false
	}
	return capitalize(m[1]), capitalize(m[2]), true
}

// RandomBirthdate returns a random birthdate string in YYYY-MM-DD format for ages 30+.
func RandomBirthdate() string {
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	year := r.Intn(1996-1985+1) + 1985
	month := r.Intn(12) + 1
	day := r.Intn(28) + 1
	return fmt.Sprintf("%04d-%02d-%02d", year, month, day)
}
